vk:
  app_id: 2462
  email: 'altermn@gmail.com'
  password: '?'
  user_id: 'newmen'
#  only_artists: ['Infected MushroOm', 'Unmorph']
#  except_artists: 'Король и Шут'
  save_dir: '/supply/Музыка/vk_playlist'
#  start:
#    artist: 'Chew Lips'
#    title: 'Karen'
#  stop:
#    artist: 'Scooter'
#    title: 'Fire'
